name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:

  # golang static analysis checks
  go-static-analysis:
    uses: dell/common-github-actions/.github/workflows/go-static-analysis.yaml@main
    name: Golang Validation
    
  common:
    name: Run gosec, unit tests, and check package coverage
    uses: dell/common-github-actions/.github/workflows/go-common.yml@add-code-tester
